#!/usr/bin/env python3
"""
png_to_artc.py  -  convert a 1-bit PNG into a ZMK nice_view art.c source.

The nice_view peripheral art slot is 140 x 68, drawn as an LVGL
LV_IMG_CF_INDEXED_1BIT image.  This script packs a PNG into exactly that
format and emits a drop-in widgets/art.c that defines `balloon` and
`mountain` (both pointing at your image, so the upstream peripheral_status.c
works unmodified - it randomly shows one or the other, and now both are you).

Bit convention matches the built-in images: a *white* source pixel is "ink"
(bit 0) and a *black* source pixel is background (bit 1), and the palette
respects CONFIG_NICE_VIEW_WIDGET_INVERTED.  Net effect:
    * normal screen (white bg)   -> dark logo on white
    * inverted screen (black bg) -> white logo on black
so the art follows whatever polarity the rest of the status screen uses.

Usage:
    python png_to_artc.py INPUT.png OUTPUT_art.c [--width 140] [--height 68]

Requires Pillow:  pip install pillow
"""

import argparse
import os
import sys

try:
    from PIL import Image
except ImportError:
    sys.exit("Pillow is required.  Install it with:  pip install pillow")

WIDTH = 140
HEIGHT = 68


def pack(img, w, h):
    """Return the packed 1-bpp bitmap bytes (MSB first, rows byte-aligned)."""
    px = img.load()
    stride = (w + 7) // 8
    out = bytearray()
    for y in range(h):
        row = bytearray(stride)
        for x in range(w):
            # white source pixel -> ink -> bit 0 ; black -> background -> bit 1
            if px[x, y] < 128:                       # black source
                row[x // 8] |= 0x80 >> (x % 8)
        out += row
    return out, stride


def to_c_array(data, per_line=15):
    lines = []
    for i in range(0, len(data), per_line):
        chunk = data[i:i + per_line]
        lines.append("        " + ", ".join(f"0x{b:02x}" for b in chunk) + ",")
    return "\n".join(lines)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("input")
    ap.add_argument("output")
    ap.add_argument("--width", type=int, default=WIDTH)
    ap.add_argument("--height", type=int, default=HEIGHT)
    args = ap.parse_args()

    w, h = args.width, args.height
    img = Image.open(args.input).convert("L").resize((w, h), Image.LANCZOS)
    img = img.point(lambda p: 255 if p >= 128 else 0, mode="1").convert("L")

    data, stride = pack(img, w, h)
    data_size = 8 + len(data)        # 8-byte palette + bitmap

    body = to_c_array(data)
    c = f"""/*
 * Generated by tools/png_to_artc.py from {os.path.basename(args.input)}
 * LVGL INDEXED_1BIT, {w}x{h}.  Do not hand-edit; re-run the script instead.
 */

#include <lvgl.h>

#ifndef LV_ATTRIBUTE_MEM_ALIGN
#define LV_ATTRIBUTE_MEM_ALIGN
#endif

#ifndef LV_ATTRIBUTE_IMG_CUSTOM_ART
#define LV_ATTRIBUTE_IMG_CUSTOM_ART
#endif

const LV_ATTRIBUTE_MEM_ALIGN LV_ATTRIBUTE_LARGE_CONST LV_ATTRIBUTE_IMG_CUSTOM_ART uint8_t
    custom_art_map[] = {{
#if CONFIG_NICE_VIEW_CUSTOM_WIDGET_INVERTED
        0xff, 0xff, 0xff, 0xff, /*Color of index 0*/
        0x00, 0x00, 0x00, 0xff, /*Color of index 1*/
#else
        0x00, 0x00, 0x00, 0xff, /*Color of index 0*/
        0xff, 0xff, 0xff, 0xff, /*Color of index 1*/
#endif

{body}
}};

const lv_img_dsc_t balloon = {{
    .header.cf = LV_IMG_CF_INDEXED_1BIT,
    .header.always_zero = 0,
    .header.reserved = 0,
    .header.w = {w},
    .header.h = {h},
    .data_size = {data_size},
    .data = custom_art_map,
}};

/* Alias so the upstream random balloon/mountain pick always shows your art. */
const lv_img_dsc_t mountain = {{
    .header.cf = LV_IMG_CF_INDEXED_1BIT,
    .header.always_zero = 0,
    .header.reserved = 0,
    .header.w = {w},
    .header.h = {h},
    .data_size = {data_size},
    .data = custom_art_map,
}};
"""
    os.makedirs(os.path.dirname(os.path.abspath(args.output)), exist_ok=True)
    with open(args.output, "w", newline="\n") as f:
        f.write(c)
    print(f"Wrote {args.output}  ({w}x{h}, {data_size} bytes, stride {stride})")


if __name__ == "__main__":
    main()
